### Get User by ID
GET http://localhost:3000/api/v1/users/0199223e-a445-7712-8ac7-6689957aa540

### Create User
POST http://localhost:3000/api/v1/users
content-type: application/json

{
    "name": "sample",
    "email": "sample@example.com",
    "password": "samplepassword",
    "primaryCurrencyCode": "USD"
}