services:
  db:
    image: postgres:15-alpine
    container_name: db_api_subscription_manager
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  cache_redis:
    image: redis:alpine
    container_name: cache_redis_subscription_manager
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: .
    container_name: api_subscription_manager
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
      - REDIS_URL=redis://cache_redis:6379
    env_file:
      - .env.dev
    command: npm run dev
    depends_on:
      - db
      - cache_redis
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  postgres_data:
  redis_data: