### GET All Categories
### Only Admins can access this endpoint
GET http://localhost:3000/api/v1/categories?page=1&limit=5
Origin: http://localhost:3000

### Get Categories by ID
### Only Admins and User themselves can access this endpoint
GET http://localhost:3000/api/v1/categories/3
Origin: http://localhost:3000

### Create Categories
### Only Admins and User themselves can access this endpoint
POST http://localhost:3000/api/v1/categories
Origin: http://localhost:3000
content-type: application/json

{
    "name": "Entertainment"
}

### Update Categories
### Only Admins and User themselves can access this endpoint
PUT http://localhost:3000/api/v1/categories/6
Origin: http://localhost:3000
content-type: application/json

{
    "name": "musica"
}

### Delete Categories
### Only Admins and User themselves can access this endpoint
DELETE http://localhost:3000/api/v1/categories/9999
Origin: http://localhost:3000