### GET All Categories
GET http://localhost:3000/api/v1/categories

### Get Categories by ID
GET http://localhost:3000/api/v1/categories/1

### Create Categories
POST http://localhost:3000/api/v1/categories
content-type: application/json

{
    "userId": "01994fcc-a3da-74c0-a945-9871328f21b9",
    "name": "streaming"
}

### Update Categories
PUT http://localhost:3000/api/v1/categories/27
content-type: application/json

{
    "name": "musica"
}

### Delete Categories
DELETE http://localhost:3000/api/v1/categories/27