### GET All Currencies
GET http://localhost:3000/api/v1/currencies
Origin: http://localhost:3000

### Get Currencies by ID
GET http://localhost:3000/api/v1/currencies/DMA
Origin: http://localhost:3000

### Create Currencies
POST http://localhost:3000/api/v1/currencies
Origin: http://localhost:3000
content-type: application/json

{
    "code": "DMA",
    "name": "Yen Japanese",
    "symbol": "¥"
}

### Update Currencies
PUT http://localhost:3000/api/v1/currencies/DMA
Origin: http://localhost:3000
content-type: application/json

{
    "name": "DMA",
    "symbol": "¥"
}

### Delete Currencies
DELETE http://localhost:3000/api/v1/currencies/DMA
Origin: http://localhost:3000