### GET All Users
GET http://localhost:3000/api/v1/users
Origin: http://localhost:3000

### Get User by ID
GET http://localhost:3000/api/v1/users/019b3dfd-cfaa-7de5-9eeb-8bc1186b1d68
Origin: http://localhost:3000

### Create User
POST http://localhost:3000/api/v1/users
Origin: http://localhost:3000
content-type: application/json

{
    "name": "Carlos Doe",
    "email": "carlos.doe@example.com",
    "password": "Coleccion12",
    "primaryCurrencyCode": "USD"
}

### Update User
PUT http://localhost:3000/api/v1/users/019b3dfd-cfaa-7de5-9eeb-8bc1186b1d68
Origin: http://localhost:3000
content-type: application/json

{
    "name": "Carlos Guevara",
    "email": "carlos.doe@example.com",
    "password": "Coleccion12",
    "primaryCurrencyCode": "EUR"
}

### Delete User
DELETE http://localhost:3000/api/v1/users/019b3dfd-cfaa-7de5-9eeb-8bc1186b1d68
Origin: http://localhost:3000