-- AlterTable
ALTER TABLE "public"."Currency" ADD COLUMN     "exchangeRateToUSD" DECIMAL(11,4) NOT NULL DEFAULT 1.0000,
ADD COLUMN     "rateUpdatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
